import {regions,regionAt,land,height,landmarks,makeWorld,movePlayer} from './world.js';
const $=s=>document.querySelector(s), canvas=$('#world'), c=canvas.getContext('2d'), mini=$('#minimap'), mc=mini.getContext('2d');
const objects=makeWorld(), birds=Array.from({length:16},(_,i)=>({x:Math.sin(i*17)*48,z:Math.cos(i*13)*43,type:'bird',phase:i*2})), keys=new Set(), particles=[], ripples=[];
let w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio,2),zoom=25,elapsed=0,last=0,started=false,near=null,day=9,modal=false,sound=false,audio,wind=0,fox=false,toastTimer,returnFocus;
let found=new Set();try{const saved=JSON.parse(localStorage.getItem('elsewhere-v1')||'[]');if(Array.isArray(saved))found=new Set(saved.filter(id=>landmarks.some(l=>l.id===id)));}catch{}
const p={x:0,z:7,vx:0,vz:0,y:0,vy:0,face:1}, camera={x:0,z:5}, stick={x:0,y:0};
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio,2);canvas.width=w*dpr;canvas.height=h*dpr;zoom=w<760?21:28;c.setTransform(dpr,0,0,dpr,0,0);}
addEventListener('resize',resize);resize();
function project(x,z,y=0){return {x:w*.52+(x-camera.x-z+camera.z)*zoom*.86,y:h*.51+(x-camera.x+z-camera.z)*zoom*.43-(height(x,z)+y)*zoom};}
function poly(points,color,stroke){c.beginPath();points.forEach((v,i)=>i?c.lineTo(v[0],v[1]):c.moveTo(v[0],v[1]));c.closePath();c.fillStyle=color;c.fill();if(stroke){c.strokeStyle=stroke;c.stroke();}}
function ellipse(x,y,rx,ry,color){c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fillStyle=color;c.fill();}
function line(x,y,xx,yy,color,width=2){c.beginPath();c.moveTo(x,y);c.lineTo(xx,yy);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
function box(x,y,ww,hh,dd,top,left,right){poly([[x,y-hh],[x+ww,y-hh-dd],[x+ww+dd,y-hh],[x+dd,y-hh+dd]],top);poly([[x,y-hh],[x+dd,y-hh+dd],[x+dd,y+dd],[x,y]],left);poly([[x+dd,y-hh+dd],[x+ww+dd,y-hh],[x+ww+dd,y],[x+dd,y+dd]],right);}
function tree(o,sx,sy){const s=o.s*zoom/26, sw=Math.sin(elapsed*1.1+o.x)*2*s;ellipse(sx,sy,21*s,9*s,'#314f3720');line(sx,sy,sx+sw,sy-43*s,'#847b59',7*s);line(sx,sy-17*s,sx-12*s,sy-40*s,'#847b59',3*s);const colors=o.r===1?['#e8a681','#f1b99a','#d99478']:o.r===4?['#929c91','#a7b29d','#82938b']:['#76a67d','#94b789','#669778'];poly([[sx-26*s+sw,sy-33*s],[sx-31*s+sw,sy-55*s],[sx-14*s+sw,sy-76*s],[sx+10*s+sw,sy-80*s],[sx+29*s+sw,sy-58*s],[sx+24*s+sw,sy-35*s],[sx,sy-27*s]],colors[0]);poly([[sx-31*s+sw,sy-55*s],[sx-14*s+sw,sy-76*s],[sx+10*s+sw,sy-80*s],[sx+3*s+sw,sy-48*s],[sx-12*s+sw,sy-38*s]],colors[1]);poly([[sx+3*s+sw,sy-48*s],[sx+10*s+sw,sy-80*s],[sx+29*s+sw,sy-58*s],[sx+24*s+sw,sy-35*s],[sx,sy-27*s]],colors[2]);if(o.r===1){for(let i=0;i<3;i++)ellipse(sx+(-15+i*14)*s+sw,sy-(47+i%2*15)*s,3*s,4*s,'#eb7951');}}
function house(x,y){const s=zoom/26;ellipse(x,y,51*s,21*s,'#314f3720');poly([[x-35*s,y-47*s],[x+3*s,y-30*s],[x+3*s,y+12*s],[x-35*s,y-5*s]],'#f2dfb0');poly([[x+3*s,y-30*s],[x+40*s,y-48*s],[x+40*s,y-6*s],[x+3*s,y+12*s]],'#d3bd8b');poly([[x-46*s,y-47*s],[x-7*s,y-76*s],[x+44*s,y-55*s],[x+3*s,y-24*s]],'#be6f4d');poly([[x+3*s,y-24*s],[x+44*s,y-55*s],[x+46*s,y-45*s],[x+6*s,y-14*s]],'#995b43');poly([[x-46*s,y-47*s],[x-7*s,y-76*s],[x-2*s,y-72*s],[x-39*s,y-41*s]],'#d8875c');poly([[x+14*s,y-15*s],[x+27*s,y-21*s],[x+27*s,y+1*s],[x+14*s,y+7*s]],'#63796d');poly([[x-25*s,y-29*s],[x-13*s,y-24*s],[x-13*s,y-12*s],[x-25*s,y-17*s]],'#82acaa');line(x-19*s,y-27*s,x-19*s,y-15*s,'#f7e8b7',2*s);box(x+15*s,y-54*s,7*s,27*s,7*s,'#e5ccaa','#b79676','#a68d70');}
function person(x,y,color='#dc7249',isPlayer=false){const s=zoom/27,step=isPlayer?Math.sin(elapsed*14)*Math.min(1,Math.hypot(p.vx,p.vz)/4):Math.sin(elapsed*2)*.15;ellipse(x,y+(isPlayer?p.y*zoom:0),10*s,4*s,'#29493430');line(x-4*s,y-7*s,x-5*s+step*4,y,'#3a5350',4*s);line(x+4*s,y-7*s,x+5*s-step*4,y,'#3a5350',4*s);poly([[x-8*s,y-25*s],[x+6*s,y-25*s],[x+9*s,y-8*s],[x-8*s,y-8*s]],color);line(x-7*s,y-21*s,x-11*s-step*4,y-12*s,'#d9ac80',4*s);line(x+7*s,y-21*s,x+10*s+step*4,y-13*s,'#d9ac80',4*s);ellipse(x,y-31*s,7*s,8*s,'#edc299');ellipse(x,y-37*s,9*s,4*s,'#f6df9b');ellipse(x,y-40*s,6*s,4*s,'#edd08a');ellipse(x+(isPlayer?p.face:1)*3*s,y-31*s,1*s,1*s,'#354637');if(isPlayer){poly([[x-8*s,y-23*s],[x-2*s,y-22*s],[x-2*s,y-11*s],[x-9*s,y-12*s]],'#a75336');}}
function flower(x,y,color,s=1){line(x,y,x,y-8*s,'#76946a',1);ellipse(x,y-9*s,3*s,2*s,color);ellipse(x+2*s,y-7*s,2*s,2*s,color);}
function landmark(o,x,y){const s=zoom/26,t=elapsed;
 if(o.type==='tree'){tree({...o,r:1,s:1.6},x,y);}
 if(o.type==='bell'){line(x-20*s,y,x-20*s,y-56*s,'#857d59',6*s);line(x+20*s,y,x+20*s,y-56*s,'#857d59',6*s);line(x-23*s,y-56*s,x+23*s,y-56*s,'#776e51',6*s);line(x,y-55*s,x,y-42*s,'#6f765b',2*s);poly([[x-8*s,y-44*s],[x+8*s,y-44*s],[x+12*s,y-27*s],[x-12*s,y-27*s]],'#deb95f');ellipse(x,y-27*s,13*s,4*s,'#c89b46');line(x,y-25*s,x,y-10*s,'#a58b53',2*s);}
 if(o.type==='picnic'){poly([[x-35*s,y],[x,y-18*s],[x+36*s,y],[x,y+18*s]],'#e4b58b');for(let i=-2;i<3;i++)line(x+i*10*s-10*s,y-10*s,x+i*10*s+10*s,y+10*s,'#f3d6ac',2);ellipse(x,y,12*s,6*s,'#f9ebc7');ellipse(x,y-2*s,6*s,3*s,'#e29852');person(x+34*s,y-4*s,'#6d8f9b');}
 if(o.type==='fox'){let fx=fox?Math.sin(t)*5:0;ellipse(x+fx,y,15*s,5*s,'#46634420');poly([[x-12*s+fx,y-5*s],[x-24*s+fx,y-18*s],[x-21*s+fx,y-4*s],[x-8*s+fx,y+1*s]],'#dd8d53');ellipse(x+fx,y-8*s,12*s,7*s,'#d7864c');poly([[x+5*s+fx,y-11*s],[x+4*s+fx,y-23*s],[x+11*s+fx,y-18*s],[x+18*s+fx,y-22*s],[x+18*s+fx,y-9*s],[x+12*s+fx,y-3*s]],'#df975e');ellipse(x+13*s+fx,y-10*s,3*s,2*s,'#f9dfac');}
 if(o.type==='pond'){ellipse(x,y,90*s,42*s,'#9ab79b');ellipse(x,y-2*s,80*s,35*s,'#80b9b9');ellipse(x-7*s,y-4*s,63*s,27*s,'#91c8c4');for(let i=0;i<4;i++){const xx=x+Math.sin(t*.4+i*3)*40*s,yy=y+Math.cos(i)*20*s;line(xx,yy,xx+13*s,yy,'#d5e5ca',1);}ellipse(x+43*s,y+10*s,9*s,4*s,'#698f73');flower(x+43*s,y+9*s,'#eed0cb',1.5);}
 if(o.type==='boat'){for(let i=0;i<6;i++)poly([[x-23*s,y+i*5*s],[x+23*s,y-19*s+i*5*s],[x+23*s,y-15*s+i*5*s],[x-23*s,y+4*s+i*5*s]],'#ae9772');poly([[x+30*s,y+20*s],[x+50*s,y+14*s],[x+42*s,y+26*s]],'#f8edcd');}
 if(o.type==='windmill'){poly([[x-20*s,y],[x+21*s,y],[x+12*s,y-87*s],[x-10*s,y-87*s]],'#ead6a4');poly([[x-21*s,y-84*s],[x,y-105*s],[x+23*s,y-84*s]],'#b77750');const a=t*(wind>.1?1.7:.25);for(let i=0;i<4;i++){c.save();c.translate(x,y-76*s);c.rotate(a+i*Math.PI/2);poly([[0,-3*s],[48*s,-3*s],[48*s,7*s],[9*s,4*s]],'#f5e8c7');line(0,0,50*s,0,'#8d815b',2*s);c.restore();}ellipse(x,y-76*s,5*s,5*s,'#9d8b60');}
 if(o.type==='npc')person(x,y,'#8a9e83');
 if(o.type==='flowers'){for(let i=0;i<38;i++)flower(x+Math.sin(i*13)*46*s,y+Math.cos(i*7)*22*s,['#a798bc','#baacce','#e0c4ca'][i%3],1.4);}
 if(o.type==='stones'){for(let i=0;i<5;i++){const xx=x+(i-2)*17*s,yy=y+Math.sin(i)*10*s;poly([[xx-7*s,yy],[xx-9*s,yy-20*s-i*4*s],[xx,yy-29*s-i*4*s],[xx+9*s,yy-19*s-i*4*s],[xx+7*s,yy]],['#8d9b9c','#99a6a0','#a6b3ae'][i%3]);line(xx-3*s,yy-14*s,xx+3*s,yy-16*s,'#d5ded0',2);}}
 if(o.type==='telescope'){line(x,y-20*s,x-14*s,y+4*s,'#8b8167',3*s);line(x,y-20*s,x+14*s,y+4*s,'#8b8167',3*s);line(x,y-20*s,x,y+9*s,'#8b8167',3*s);line(x-9*s,y-20*s,x+19*s,y-39*s,'#5c8887',11*s);line(x+17*s,y-39*s,x+21*s,y-41*s,'#d6c784',13*s);}
 if(o.type==='camp'){ellipse(x,y,23*s,11*s,'#8f9b80');line(x-12*s,y-5*s,x+12*s,y+5*s,'#806f51',6*s);line(x+12*s,y-5*s,x-12*s,y+5*s,'#8e7754',6*s);poly([[x-9*s,y],[x-7*s,y-15*s],[x-2*s,y-11*s],[x+4*s,y-27*s-Math.sin(t*8)*4],[x+10*s,y-10*s],[x+7*s,y+1*s]],'#eca553');poly([[x-4*s,y],[x+2*s,y-15*s],[x+5*s,y]],'#f7d680');poly([[x+27*s,y-9*s],[x+51*s,y-42*s],[x+81*s,y-8*s]],'#d6b478');poly([[x+51*s,y-42*s],[x+81*s,y-8*s],[x+104*s,y-23*s],[x+76*s,y-52*s]],'#b19c69');}
 if(!found.has(o.id)){const yy=y-(o.type==='windmill'?122: o.type==='tree'?135:68)*s+Math.sin(t*2+o.x)*3;c.fillStyle='#fff7d8';c.font=`${16*s}px Georgia`;c.textAlign='center';c.fillText('✧',x,yy);}
}
function terrain(){
 c.fillStyle='#b1d2c7';c.fillRect(0,0,w,h);
 for(let i=0;i<35;i++){const x=(i*177+elapsed*5)%(w+100)-50,y=(i*93)%(h);line(x,y,x+25,y,'#d2e4cf60',1);}
 const tiles=[];const step=1.5;
 for(let x=-66;x<66;x+=step)for(let z=-63;z<63;z+=step){if(!land(x+step/2,z+step/2))continue;const pt=project(x,z);if(pt.x < -180||pt.x>w+180||pt.y< -130||pt.y>h+150)continue;tiles.push({x,z,d:x+z});}
 tiles.sort((a,b)=>a.d-b.d);
 for(const {x,z} of tiles){const pts=[[x,z],[x+step,z],[x+step,z+step],[x,z+step]].map(([xx,zz])=>project(xx,zz));const r=regionAt(x,z);let color=r.color;if(Math.abs(z-Math.sin(x*.065)*5)<2.4||Math.abs(x-Math.sin(z*.09)*7)<2.4)color='#d9d2a3';if(!land(x+step,z+step)) {poly([[pts[2].x,pts[2].y],[pts[3].x,pts[3].y],[pts[3].x,pts[3].y+21],[pts[2].x,pts[2].y+21]],'#d3c6a0');}poly(pts.map(q=>[q.x,q.y]),color,color);}
}
function render(){
 terrain();
 const all=[...objects,...landmarks,...birds,{x:p.x,z:p.z,type:'player'}].sort((a,b)=>(a.x+a.z)-(b.x+b.z));
 for(const o of all){const q=project(o.x,o.z,o.type==='player'?p.y:0);if(q.x< -160||q.x>w+160||q.y< -100||q.y>h+190)continue;c.save();if(o.type==='tree'&&o.x+o.z>p.x+p.z&&Math.hypot(q.x-project(p.x,p.z).x,(q.y-project(p.x,p.z).y)-45)<65)c.globalAlpha=.5;
 if(o.type==='bird'){const flap=Math.sin(elapsed*8+o.phase)*4;line(q.x-5,q.y-5-flap,q.x,q.y-5,'#f4ebd0',2);line(q.x,q.y-5,q.x+5,q.y-5-flap,'#f4ebd0',2);}else if(o.type==='player')person(q.x,q.y,'#de734a',true);else if(o.id)landmark(o,q.x,q.y);else if(o.type==='tree')tree(o,q.x,q.y);else if(o.type==='house')house(q.x,q.y);else if(o.type==='rock'){const s=o.s*10;poly([[q.x-s,q.y],[q.x-s*.7,q.y-s],[q.x+s*.3,q.y-s*1.3],[q.x+s,q.y-s*.4],[q.x+s*.8,q.y+s*.2]],'#9ba58b');poly([[q.x-s,q.y],[q.x-s*.7,q.y-s],[q.x+s*.3,q.y-s*1.3],[q.x,q.y]],'#b3b99d');}else if(o.type==='flower')flower(q.x,q.y,o.r===4?'#b09ac1':'#f1dc91',o.s);else {line(q.x-3,q.y,q.x-5,q.y-5,'#829f6b',1);line(q.x,q.y,q.x+2,q.y-7,'#829f6b',1);}c.restore();}
 for(const r of ripples){if(r.age<0)continue;const q=project(r.x,r.z);c.beginPath();c.ellipse(q.x,q.y,r.age*40,r.age*17,0,0,Math.PI*2);c.strokeStyle=`rgba(255,245,205,${Math.max(0,1-r.age/2)})`;c.lineWidth=2;c.stroke();}
 for(const v of particles){const q=project(v.x,v.z,v.y);ellipse(q.x,q.y,v.size||3, v.size||3,v.color);}
 const night=Math.max(0,Math.cos((day-1)/24*Math.PI*2))*.32;if(night>0){c.fillStyle=`rgba(31,48,83,${night})`;c.fillRect(0,0,w,h);for(let i=0;i<25;i++){const q=project(p.x+Math.sin(i*5)*15,p.z+Math.cos(i*3)*15,1+Math.sin(elapsed+i)*.5);ellipse(q.x,q.y,2,2,`rgba(255,232,142,${.4+Math.sin(elapsed*2+i)*.35})`);}}
 // Soft drifting cloud shadows.
 for(let i=0;i<4;i++){const xx=(i*430+elapsed*9)%(w+500)-250,yy=(i*217)%(h+100);ellipse(xx,yy,115,33,'#f5f3db0c');}
 drawMap(mc,180,130);
}
function drawMap(ctx,mw,mh){ctx.fillStyle='#bad4c7';ctx.fillRect(0,0,mw,mh);const sc=Math.min(mw/150,mh/145);for(let x=-66;x<66;x+=3)for(let z=-63;z<63;z+=3){if(!land(x,z))continue;ctx.fillStyle=regionAt(x,z).color;ctx.fillRect(mw/2+x*sc,mh/2+z*sc,3.5*sc,3.5*sc);}ctx.strokeStyle='#f0e0b4';ctx.lineWidth=mw>200?5:2;ctx.beginPath();for(let x=-60;x<61;x++)ctx.lineTo(mw/2+x*sc,mh/2+Math.sin(x*.065)*5*sc);ctx.stroke();ctx.beginPath();for(let z=-59;z<59;z++)ctx.lineTo(mw/2+Math.sin(z*.09)*7*sc,mh/2+z*sc);ctx.stroke();for(const l of landmarks){ctx.fillStyle=found.has(l.id)?'#fcf0ce':'#758c71';ctx.beginPath();ctx.arc(mw/2+l.x*sc,mh/2+l.z*sc,mw>200?5:2,0,Math.PI*2);ctx.fill();}if(mw>200){ctx.font='12px Arial';ctx.textAlign='center';for(const r of regions){ctx.fillStyle='#2e493d';ctx.fillText(r.name,mw/2+r.x*sc,mh/2+r.z*sc-18);}}ctx.fillStyle='#d26944';ctx.strokeStyle='#fff8de';ctx.lineWidth=2;ctx.beginPath();ctx.arc(mw/2+p.x*sc,mh/2+p.z*sc,mw>200?7:4,0,Math.PI*2);ctx.fill();ctx.stroke();}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function save(){try{localStorage.setItem('elsewhere-v1',JSON.stringify([...found]));}catch{}$('#count').textContent=found.size;}
function tone(freq,duration=.4,delay=0){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,audio.currentTime+delay);g.gain.linearRampToValueAtTime(.07,audio.currentTime+delay+.02);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+delay+duration);o.connect(g);g.connect(audio.destination);o.start(audio.currentTime+delay);o.stop(audio.currentTime+delay+duration);}
function burst(x,z,color='#f7df96',n=24){for(let i=0;i<n;i++)particles.push({x,z,y:1,vx:(Math.random()-.5)*6,vz:(Math.random()-.5)*6,vy:2+Math.random()*4,life:2,color,size:2+Math.random()*2});}
function show(title,content,label='FIELD NOTES'){returnFocus=document.activeElement;modal=true;keys.clear();$('#modal-title').textContent=title;$('#modal-label').textContent=label;$('#modal-content').innerHTML=content;$('#overlay').classList.remove('hidden');$('#close').focus();}
function close(){modal=false;$('#overlay').classList.add('hidden');returnFocus?.focus();}
function interact(){if(!started||modal||!near)return;const l=near,fresh=!found.has(l.id);found.add(l.id);save();burst(l.x,l.z);[392,493.88,587.33].forEach((n,i)=>tone(n,.7,i*.1));if(fresh)toast(`✧  Discovered: ${l.name}  ·  ${found.size} / 12`);else toast(l.note);
 if(l.kind==='friend')show(l.speaker,`<p>“${l.dialog}”</p><p><em>${l.note}</em></p>`,'A FRIEND ALONG THE WAY');
 if(l.kind==='bell'){for(let i=0;i<4;i++)ripples.push({x:l.x,z:l.z,age:-i*.3});tone(784,2);}
 if(l.kind==='fruit')burst(l.x,l.z,'#eb9763',35);
 if(l.kind==='fox'){fox=true;toast('The fox does a happy little dance. Friendship looks good on you.');}
 if(l.kind==='pond'||l.kind==='boat')for(let i=0;i<6;i++)ripples.push({x:l.x+i*.5,z:l.z-i*.4,age:-i*.16});
 if(l.kind==='windmill')wind=15;
 if(l.kind==='flowers')burst(l.x,l.z,'#e3c3ef',80);
 if(l.kind==='stones')[261.63,329.63,392,523.25,659.25].forEach((n,i)=>tone(n,1,i*.18));
 if(l.kind==='camp'){day=19;show('Stay for the sunset.', '<p>You warm your hands by the fire. Somewhere below, the whole island is going about its small, wonderful business.</p><p>Take a breath. There is no next objective.</p>','CLOUDWATCH RIDGE · 19:00');}
 if(l.kind==='cloud')show('The sky has no plans either.','<p>A whale. A teapot. An enormous sleeping fox.</p><p>You watch the clouds drift over the island, and for a moment it feels as though the world is standing still just for you.</p>','A DIFFERENT PERSPECTIVE');
 if(found.size===12&&fresh)toast('✧ Every moment collected. The world is still yours to wander.');
}
function begin(){started=true;$('#welcome').classList.add('hidden');toast('There’s no rush. Follow a path, or make your own.');}
function jump(){if(started&&!modal&&p.y===0){p.vy=7;tone(240,.12);}}
function journal(){show('A pocketful of moments',`<p>${found.size} of 12 little reasons to take the long way home. Discoveries are saved on this device.</p><div class="journal-grid">${landmarks.map(l=>`<article class="entry ${found.has(l.id)?'':'locked'}"><b>${found.has(l.id)?'✧ '+l.name:'◇ An undiscovered moment'}</b><p>${found.has(l.id)?l.note:regions[l.region].name}</p></article>`).join('')}</div>`);}
function map(){show('There’s more out there.','<canvas id="bigmap" width="580" height="480"></canvas><p>The orange dot is you. Pale dots are memories you’ve made; dark dots are invitations. North is toward the top of this map.</p>','YOUR VERY UNOFFICIAL ISLAND MAP');drawMap($('#bigmap').getContext('2d'),580,480);}
$('#begin').onclick=begin;$('#close').onclick=close;$('#overlay').onclick=e=>{if(e.target===$('#overlay'))close();};$('#journal-open').onclick=journal;$('#map-open').onclick=map;$('#help').onclick=()=>show('A little room to roam.','<p><b>WASD / Arrow keys</b> — move in the direction of the screen<br><b>Shift</b> — run with a little momentum<br><b>Space</b> — jump<br><b>E</b> — interact when a prompt appears<br><b>M</b> — island map · <b>J</b> — discovery journal<br><b>Escape</b> — close a panel</p><p>Six neighborhoods. Twelve discoveries. No timers, deliveries, or wrong turns. Follow the paths or head into the wilderness. On touch screens, use the joystick and the two action buttons.</p>','MAKE YOURSELF AT HOME');
$('#sound').onclick=()=>{sound=!sound;if(sound){audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();tone(392,.8);tone(587,.8,.2);}$('#sound').innerHTML=`♫ <span>Sound ${sound?'on':'off'}</span>`;$('#sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');};
addEventListener('keydown',e=>{if(modal){if(e.code==='Escape')close();if(e.code==='Tab'){const focusable=[...$('.modal').querySelectorAll('button,[href],[tabindex="0"]')];if(focusable.length===1){e.preventDefault();focusable[0].focus();}}return;}if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space')jump();if(e.code==='KeyE')interact();if(e.code==='KeyM')map();if(e.code==='KeyJ')journal();if(e.code==='Enter'&&!started)begin();});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();stick.x=stick.y=0;});
const joy=$('#joystick');function stickMove(e){const r=joy.getBoundingClientRect();stick.x=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/30));stick.y=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/30));joy.firstElementChild.style.transform=`translate(${stick.x*20}px,${stick.y*20}px)`;}
joy.onpointerdown=e=>{joy.setPointerCapture(e.pointerId);stickMove(e);};joy.onpointermove=e=>{if(joy.hasPointerCapture(e.pointerId))stickMove(e);};joy.onpointerup=joy.onpointercancel=()=>{stick.x=stick.y=0;joy.firstElementChild.style.transform='';};$('#touch-jump').onpointerdown=e=>{e.preventDefault();jump();};$('#touch-interact').onclick=interact;
function update(dt){elapsed+=dt;for(const b of birds){b.x+=Math.sin(elapsed*.3+b.phase)*dt*.7;b.z+=Math.cos(elapsed*.3+b.phase)*dt*.7;}if(!modal&&started){day=(day+dt*.025)%24;const sx=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x,sy=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stick.y;let dx=(sx+sy)*.7071,dz=(sy-sx)*.7071;const mag=Math.max(1,Math.hypot(dx,dz)),speed=keys.has('ShiftLeft')||keys.has('ShiftRight')?10:6;dx=dx/mag*speed;dz=dz/mag*speed;const mix=1-Math.exp(-dt*10);p.vx+=(dx-p.vx)*mix;p.vz+=(dz-p.vz)*mix;movePlayer(p,p.vx*dt,p.vz*dt,objects);if(sx)p.face=Math.sign(sx);p.vy-=18*dt;p.y=Math.max(0,p.y+p.vy*dt);if(p.y===0)p.vy=0;}
 camera.x+=(p.x-camera.x)*(1-Math.exp(-dt*4));camera.z+=(p.z-camera.z)*(1-Math.exp(-dt*4));wind=Math.max(0,wind-dt);
 for(let i=particles.length-1;i>=0;i--){const v=particles[i];v.x+=v.vx*dt;v.z+=v.vz*dt;v.y+=v.vy*dt;v.vy-=4*dt;v.life-=dt;if(v.life<0)particles.splice(i,1);}
 for(let i=ripples.length-1;i>=0;i--){ripples[i].age+=dt;if(ripples[i].age>2)ripples.splice(i,1);}
 near=landmarks.find(l=>Math.hypot(l.x-p.x,l.z-p.z)<(l.type==='pond'?5:3.5));$('#prompt').classList.toggle('hidden',!near||!started||modal);if(near)$('#prompt span').textContent=near.action;
 const region=regionAt(p.x,p.z);$('#region').textContent=region.name;$('#region-sub').textContent=region.sub;$('#clock').textContent=`${Math.floor(day).toString().padStart(2,'0')}:${Math.floor(day%1*60).toString().padStart(2,'0')}`;$('#sun').textContent=day>6&&day<19?'☀':'☾';$('#weather').textContent=day>6&&day<19?'a lovely day to get lost':'the fireflies are out';
 if(sound&&Math.floor(elapsed*10)%80===0&&Math.floor((elapsed-dt)*10)%80!==0)tone([261.63,329.63,392,523.25][Math.floor(Math.random()*4)],2);
}
function frame(now){const dt=Math.min((now-last)/1000||.016,.05);last=now;update(dt);render();requestAnimationFrame(frame);}save();requestAnimationFrame(frame);
// A small read-only diagnostics surface for browser smoke tests.
window.elsewhere={get state(){return {started,player:{...p},discoveries:[...found],region:regionAt(p.x,p.z).name,objects:objects.length,landmarks:landmarks.length};}};
